[package]
name = 'sparse-bitfield'
version = "0.1.0"
license = 'MIT OR Apache-2.0'
readme = 'README.md'
edition = '2018'

[dependencies]
memory-pager = '0.9.0'

[dev-dependencies]
proptest = '0.10.0'
tempfile = "3.1.0"
