[package]
name = 'sparser-bitfield'
version = "0.1.0"
license = 'MIT OR Apache-2.0'
readme = 'README.md'
edition = '2018'

[dependencies]
skiplist = "0.4.0"

[dev-dependencies]
proptest = "0.10.0"
rand = "0.8.4"
